spring.application.name=Trending
server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/thread_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Rahul1818}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.hibernate.format_sql=false

jwt.secret=${JWT_SECRET:rahulranjannaamhaimerabnatatahusoftwarekoiboltayrey}
jwt.expiration=86400000

logging.level.org.springframework.security=WARN
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
